### PR TITLE
Modules imported into a fabfile might not have a __doc__ variable

### PR DESCRIPTION
**Pull request by dreadatour**
```
username@localhost:~/work/project/$ fab mytask
Traceback (most recent call last):
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 667, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 178, in load_fabfile
    docstring, new_style, classic, default = load_tasks_from_module(imported)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 199, in load_tasks_from_module
    new_style, classic, default = extract_tasks(imported_vars)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 232, in extract_tasks
    docs, newstyle, classic, default = load_tasks_from_module(obj)
  File "/Users/username/work/project/env/lib/python2.7/site-packages/fabric/main.py", line 200, in load_tasks_from_module
    return imported.__doc__, new_style, classic, default
AttributeError: cffi library '_openssl' has no function, constant or global variable named '__doc__'
```

### CODE REVIEW

**Comment by bitprophet** [comment]
That's an amazing traceback. Is it just because `_openssl` is that many chained imports deep from the fabfile? 😆 

Honestly surprised this went without triggering such an error for so long - thanks for the catch!

**Comment by dreadatour** [comment]
> That's an amazing traceback. Is it just because _openssl is that many chained imports deep from the fabfile?
Yeah, some old projects could be very surprising :)

> Honestly surprised this went without triggering such an error for so long - thanks for the catch!
Me too! Do I need something except tests to make this issue released?

**Comment by bitprophet** [comment]
Tests would be great, a changelog entry would also be good but I can supply that at confirm+merge time. Otherwise, I'll get to it at next bugfix roundup. Thanks!

**Comment by jamesongithub** [comment]
@bitprophet can we get this in?

**Comment by bitprophet** [comment]
Have a sprinter looking at writing tests for this now! Otherwise, it's still in the milestone and Fab 1 is overdue for a bugfix release, so it will happen.

**Comment by michaeldayreads** [comment]
@bitprophet - are tests still needed for this? Looking to cut my teeth on a contribution.

**Pull request closed without merging**
