### PR TITLE
WrappedCallableTask.__details__() support for multi-decorated objects

### PR DESCRIPTION
**Pull request by mvk**
- fixes fabric/fabric #971
 - fixes fabric/fabric #1032

### CODE REVIEW

**Comment by mvk** [comment]
The failure happens after the tests I've added passed. this is false positive on tests failure :(

**Comment by bitprophet** [comment]
Travis seems to have broken things across the board for our test suite, so no that's not your fault. Thanks for the submission :) Also, what's up with #1287, is that supposed to supersede this one or was it a mistaken push?

**Comment by mvk** [comment]
Hi.
Not entirely, but the last commit out of these 3 is probably a Travis
phantom fix :)

**Comment by bitprophet** [comment]
Confirmed a downstream dev dependency broke our tests, thankfully I also run taht project now so I fixed it :3 kickstarted travis again to see what happens.

**Comment by mvk** [comment]
Glad to hear. Do you want me to do anything or you're OK with cherry
picking?

**Pull request closed without merging**
