### PR TITLE
[v2] Add close method to group objects

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by kyrias** [comment]
Hm, pypy job failed while due to a network error when installing the dependencies.

**Comment by kyrias** [comment]
Ping?

**Comment by kyrias** [comment]
@bitprophet Could this be reopened?

**Comment by bitprophet** [comment]
Not sure why this got closed, honestly, so sure!

**Comment by bitprophet** [comment]
Oh, I see. It's something specific on Github's end, possibly due to branch moving/renaming (which is probably also why I do not remember explicitly closing it). I literally can't reopen it. But I _can_ cherry-pick the commit!

**Comment by bitprophet** [comment]
All set!

**Comment by kyrias** [comment]
Awesome, thanks.

**Pull request closed without merging**
