### PR TITLE
README example using incorrect string interpolation

### PR DESCRIPTION
**Pull request by afsec**
To work Properly, without "IndexError: tuple index out of range" Closes fabric/fabric#1777

### CODE REVIEW

**Comment by bitprophet** [comment]
This should already have been fixed (https://github.com/fabric/fabric/commit/a11e747665b4b3e91544c574f0266c88577b3aff), can you post more details/output? Are you running this under Python 2.6 or something? (Which is sadly no longer supported!)

**Comment by afsec** [comment]
```
ubuntu@fabric2:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Codename:       bionic
ubuntu@fabric2:~$ uname -a
Linux fabric2 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Not overwriting existing python script /home/ubuntu/p2k/bin/python (you must use /home/ubuntu/p2k/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting fabric
    100% |████████████████████████████████| 194kB 4.0MB/s 
Collecting cryptography>=1.1 (from fabric)
  Downloading https://files.pythonhosted.org/packages/dd/c2/3a5bfefb25690725824ade71e6b65449f0a9f4b29702cce10560f786ebf6/cryptography-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 4.9MB/s 
    100% |████████████████████████████████| 706kB 21.8MB/s 
Collecting pyasn1>=0.1.7 (from paramiko>=2.4->fabric)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 12.7MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 9.4MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46
Successfully built pycparser
Installing collected packages: invoke, pycparser, cffi, enum34, idna, asn1crypto, six, ipaddress, cryptography, pynacl, pyasn1, bcrypt, paramiko, fabric
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 fabric-2.1.3 idna-2.7 invoke-1.0.0 ipaddress-1.0.22 paramiko-2.4.1 pyasn1-0.4.3 pycparser-2.18 pynacl-1.2.1 six-1.11.0
(p2k) ubuntu@fabric2:~$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fabric import Connection
>>> result = Connection('localhost').run('uname -s')
Linux
>>> msg = "Ran {.command!r} on {.connection.host}, got stdout:\n{.stdout}"
>>> print(msg.format(result))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: tuple index out of range
>>> 
```

**Comment by bitprophet** [comment]
Hrm, yea I see it now. Weird. Thanks! This really needs to be doctested, so I need to expand the existing doctest stuff (or migrate it, might be thinking of another repo).

**Comment by bitprophet** [comment]
Extended our doctest stuff from the API docs site to the WWW one and applied to this part of the README for starters. Found a bunch of _other_ dumb mistakes, so, hooray for that!! May extend to rest of README or not, will merge soon regardless.

**Comment by bitprophet** [comment]
Cherry-picked back to 2.0 and doctested rest of README. Only found one more embarrassing mistake 😁 Thanks again!

**Comment by bitprophet** [comment]
Grumble, laid low by our setup.py long description checker on Travis - which doesn't know about Sphinx, only vanilla ReST, I think. So it's mad about the doctest stuff 😠 

https://travis-ci.org/fabric/fabric/jobs/408213027#L1475-L1556

Gotta see if there's a way around this cuz otherwise we're kinda hosed one way or another. Esp if this means it no longer renders correctly on PyPI. Might have to do something ugly like manually strip out the doctest blocks entirely when building packages...

**Comment by bitprophet** [comment]
Github also doesn't know what's up with these directives, so now our README on Github is also really ugly (the doctest setup blocks are printed literally). I hate everything about this.

**Comment by bitprophet** [comment]
Maybe I can leverage `.. include:`'s `start-after`/`end-before` type features to pull in specific bits from a doctest-oriented orphaned file, into the README. Solves the issue on the doctest-oriented file's end (no more need to include on its side), gets us a possibly workable README (though idk how well Github's rendered handles includes, if at all...).

Main issue is having solid anchors for the start/end hints. If I'm lucky, I can use what are effectively ReST comments (`.. something-with-no-trailing-commas`) that would be no-ops on the Sphinx-oriented page. Still a tad fragile but at this point that's the best I can hope for.

**Comment by bitprophet** [comment]
Wow @ today. Trying to do that and I run smack into https://bugs.python.org/issue31292 which has no solution/resolution.

This is definitely more trouble than it's worth. Time to go for the slimmed-down README + beefed-up Sphinx landing page.

**Comment by bitprophet** [comment]
Got that _apparently_ working, tho I had some stupid problems with Python 2 and string representation.

**Pull request closed without merging**
