### PR TITLE
Implement execute() for Groups

### PR DESCRIPTION
**Pull request by RedKrieg**
This implements the execute method of SerialGroup and ThreadingGroup.

I only wrote one test for now, as I'm not sure this implementation is the best approach and wanted feedback before I continued with reimplementing things like the executor to use these functions.

This implementation modifies each `connection`'s config to include those config variables normally passed as keyword arguments to `connection.run()`.  This gives us keyword control and lets the task's internal logic override us as necessary.  The cloned config is restored after execution (not sure this is the right approach here either).

I needed this functionality to begin implementing fabric/fabric#1594

### CODE REVIEW

**Comment by bitprophet** [comment]
Yea OK codecov's big comments need to go...doing that now heh.

Re: this PR itself: apologies, but I'm actually not at all sure `Group.execute` wants to be anything but a thin wrapper around an implicit `Executor`, much like how `invoke.run` is a thin wrapper around an implicit `Runner`.

This area (the overlap between Group and Executor) is not yet well defined, it needs at least some thinkin' before we start implementing it for reals. But I don't want "how to run a task" to end up split up or duplicated between those two classes, and since Executor definitely needs that management at the Invoke level (and for a bevy of other things not yet implemented, like deeper dependency management and non-Fabric-oriented task parameterization) it needs to be "the place" for those concerns, I think.

Now that I've started processing these thoughts I'll see if I can put something more firm down in at least a DDD fashion if not actual code.

**Comment by bitprophet** [comment]
Some related tickets and labels that already exist:

- pyinvoke/invoke#170
- https://github.com/pyinvoke/invoke/labels/Task%20execution

**Comment by breisig** [comment]
Can we get this functionality added and merged ASAP?

**Comment by RedKrieg** [comment]
@breisig You're welcome to maintain this functionality in your own fork using my patches.  It is both rude and unreasonable to make demands of an open source project for which you pay nothing.  If you want this functionality ASAP, implement it yourself in a way compatible with the project vision (discussed in this thread) and submit a pull request.

**Pull request closed without merging**
