### PR TITLE
Minor tweaks toward Python 3 support

### PR DESCRIPTION
**Pull request by jaraco**
These three modest changes fix syntactical errors encountered in Python 3 and a few import-time errors. Python 2.5 compatibility is maintained.

### CODE REVIEW

**Comment by hayd** [comment]
bump. Presumably this should be closed... In another issue it was mentioned that there's a branch of fabric 2.X which is going to support python 3. (Is any help required there?)

**Comment by rodrigc** [comment]
@jaraco: If you are OK with checking out the code from GitHub, and building your own copy of Fabric,
  then use the port done by @mathiasertl here: https://github.com/fabric/fabric/issues/1378
  I've tried it and it works under Python 3

**Comment by jaraco** [comment]
I very much appreciate the work of @mathiasertl to make a usable version that runs under Python 3. It's even advertised on PyPI. Unfortunately, there aren't any releases, and my attempt to contact the maintainer to make a release received no response. So for the sake of expediency, I've forked the project once again to [Fabric3bis](https://pypi.python.org/pypi/Fabric3bis) [hosted here](https://github.com/jaraco/fabric/tree/Fabric3bis).

**Comment by mathiasertl** [comment]
I am not the maintainer of this project, but if I were I would be greatly annoyed by people posting news about various forks in any (old, closed) random ticket even closely related. For the lack of release, I suggest you make a ticket on the respective github repo (which is sure to work better then private email ;-)).

**Pull request closed without merging**
