### PR TITLE
Cross-platform `default_ssh_config_path`

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@bitprophet Obviously that Travis CI build failing is some error on their end, as I've only changed two lines, one in code (which already passed Travis).

**Comment by bitprophet** [comment]
@SamuelMarks Yea that looks like a network error cascading into an actual error handling bug. Hilarious!

This looks good, and thanks. I'll merge & backport to 1.9/1.10 in a bit.

**Comment by bitprophet** [comment]
FTR that error (which should've been tanking all recent fab builds) was due to a change in paramiko master, #22, which I did just go fix such that the test suite passes for me.

Restarted the Travis job and at least one of the cells passes now, so yay for that.

Backported as discussed, hopefully this will autoclose.

**Comment by SamuelMarks** [comment]
Perfect, yeah was quite funny to see Travis failing tests on doc changes :P

**Comment by bitprophet** [comment]
Sadly I don't think it's feasible to make Travis smart enough to only run the bits of the test harness that are affected by a change (plus, due to using API docs, many code changes rightly affect doc builds anyways). We can dream :)

**Pull request closed without merging**
