### PR TITLE
Mvk/network error

### PR DESCRIPTION
**Pull request by mvk**
fixing the whole tests failure.

### CODE REVIEW

**Comment by bitprophet** [comment]
(Boo at git/hub for not noticing I cherry picked 3/4 of these already :( :()

Can you elaborate on how you're getting this error you're trying to fix in the tests? I can't recreate it / it's not clear to me. Thanks!

**Comment by mvk** [comment]
hi, Jeff.
how to reproduce:
--------8<--------8<--------8<--------8<--------8<--------8<--------
cat > fabfile.py < EOF
from fabric.decorators import task, runs_once
@runs_once
@task
def task1(p1, p2):
    """
    nice docstr
    :param p1: p1
    :param p2: p2
    """
    pass
EOF
fab -d task1
-------->8-------->8-------->8-------->8-------->8-------->8--------

OR
try the test I added on non-patched code, and you'll see the failures too.

methods decorated multiple times with decorators from fabric.decorators
(task, runs_once, parallel, etc.)
with @task making it a WrappedCallableTask not at the top, get internal
attributes messed up.
as a result, internal methods like __details__() stop working (because the
method lacks attributes tested by ismethod()/isfunction()


Sorry, I didn't exactly specify how to reproduce, relying on the related
bug reports as that source of info :-]

Makes sense now?



On Mon, Mar 9, 2015 at 11:01 PM, Jeff Forcier <notifications@github.com>
wrote:

> (Boo at git/hub for not noticing I cherry picked 3/4 of these already :(
> :()
>
> Can you elaborate on how you're getting this error you're trying to fix in
> the tests? I can't recreate it / it's not clear to me. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric/fabric/pull/1287#issuecomment-77941608>.
>



-- 
Maxim Kovgan

**Comment by mvk** [comment]
before you paste, it's [I missed 1 '<' char] :-/

*cat > fabfile.py << EOF*
*from fabric.decorators import task, runs_once*
*@runs_once*
*@task*
*def task1(p1, p2):*
*    """*
*    nice docstr*
*    :param p1: p1*
*    :param p2: p2*
*    """*
*    pass*
*EOF*
*fab -d task1*

expected is - docstring
but actual is - exception + error message.


On Mon, Mar 9, 2015 at 11:24 PM, Maxim Kovgan <kovganm@gmail.com> wrote:

> hi, Jeff.
> how to reproduce:
> --------8<--------8<--------8<--------8<--------8<--------8<--------
> cat > fabfile.py < EOF
> from fabric.decorators import task, runs_once
> @runs_once
> @task
> def task1(p1, p2):
>     """
>     nice docstr
>     :param p1: p1
>     :param p2: p2
>     """
>     pass
> EOF
> fab -d task1
> -------->8-------->8-------->8-------->8-------->8-------->8--------
>
> OR
> try the test I added on non-patched code, and you'll see the failures too.
>
> methods decorated multiple times with decorators from fabric.decorators
> (task, runs_once, parallel, etc.)
> with @task making it a WrappedCallableTask not at the top, get internal
> attributes messed up.
> as a result, internal methods like __details__() stop working (because the
> method lacks attributes tested by ismethod()/isfunction()
>
>
> Sorry, I didn't exactly specify how to reproduce, relying on the related
> bug reports as that source of info :-]
>
> Makes sense now?
>
>
>
> On Mon, Mar 9, 2015 at 11:01 PM, Jeff Forcier <notifications@github.com>
> wrote:
>
>> (Boo at git/hub for not noticing I cherry picked 3/4 of these already :(
>> :()
>>
>> Can you elaborate on how you're getting this error you're trying to fix
>> in the tests? I can't recreate it / it's not clear to me. Thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fabric/fabric/pull/1287#issuecomment-77941608>.
>>
>
>
>
> --
> Maxim Kovgan
>



-- 
Maxim Kovgan

**Comment by bitprophet** [comment]
Yea, I can't reproduce this on my Mac, the test passes and the manual fabfile+`fab -d` you posted, also works just fine.

**Comment by mvk** [comment]
hi, Jeff.

:)

Please refer to the attachment, which is a commands session listing +
outputs.

you can see fabric version there [1.10.1], from pypi.

It reproduces on 2.6.* and 2.7.* [I don't work with 3.x, but the code would
behave the same]

I am on fedora 21 at work, but have the same behavior on my mac at home
[2.7.x].

Regards!



On Mar 12, 2015 1:51 AM, "Jeff Forcier" <notifications@github.com> wrote:

> Yea, I can't reproduce this on my Mac, the test passes and the manual
> fabfile+fab -d you posted, also works just fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric/fabric/pull/1287#issuecomment-78398236>.
>

 mkovgan  ⓔ std2.6.9   master U:3  ~  mkvirtualenv -p /usr/local/python-2.7.9/bin/python2.7 fabtest2.7.9
Running virtualenv with interpreter /usr/local/python-2.7.9/bin/python2.7
New python executable in fabtest2.7.9/bin/python2.7
Also creating executable in fabtest2.7.9/bin/python
Installing setuptools, pip...done.
 mkovgan  ⓔ fabtest2.7.9   master U:3  ~  pip install Fabric
Collecting Fabric
  Using cached Fabric-1.10.1.tar.gz
Collecting paramiko>=1.10 (from Fabric)
  Using cached paramiko-1.15.2-py2.py3-none-any.whl
Collecting ecdsa>=0.11 (from paramiko>=1.10->Fabric)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting pycrypto!=2.4,>=2.1 (from paramiko>=1.10->Fabric)
  Using cached pycrypto-2.6.1.tar.gz
Installing collected packages: pycrypto, ecdsa, paramiko, Fabric
  Running setup.py install for pycrypto
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for __gmpz_init in -lgmp... no
    checking for __gmpz_init in -lmpir... no
    checking whether mpz_powm is declared... no
    checking whether mpz_powm_sec is declared... no
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for inttypes.h... (cached) yes
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking stddef.h usability... yes
    checking stddef.h presence... yes
    checking for stddef.h... yes
    checking for stdint.h... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking wchar.h usability... yes
    checking wchar.h presence... yes
    checking for wchar.h... yes
    checking for inline... inline
    checking for int16_t... yes
    checking for int32_t... yes
    checking for int64_t... yes
    checking for int8_t... yes
    checking for size_t... yes
    checking for uint16_t... yes
    checking for uint32_t... yes
    checking for uint64_t... yes
    checking for uint8_t... yes
    checking for stdlib.h... (cached) yes
    checking for GNU libc compatible malloc... yes
    checking for memmove... yes
    checking for memset... yes
    configure: creating ./config.status                                                                                         [64/219]
    config.status: creating src/config.h
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/MD2.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD2.so
    building 'Crypto.Hash._MD4' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/MD4.c -o build/temp.linux-x86_64-2.7/src/MD4.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/MD4.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD4.so
    building 'Crypto.Hash._SHA256' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/SHA256.c -o build/temp.linux-x86_64-2.7/src/SHA256.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/SHA256.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA256.so
    building 'Crypto.Hash._SHA224' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/SHA224.c -o build/temp.linux-x86_64-2.7/src/SHA224.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/SHA224.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA224.so
    building 'Crypto.Hash._SHA384' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/SHA384.c -o build/temp.linux-x86_64-2.7/src/SHA384.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/SHA384.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA384.so
    building 'Crypto.Hash._SHA512' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/SHA512.c -o build/temp.linux-x86_64-2.7/src/SHA512.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/SHA512.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA512.so
    building 'Crypto.Hash._RIPEMD160' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -DPCT_LITTLE_ENDIAN=1 -I
src/ -I/usr/local/python-2.7.9/include/python2.7 -c src/RIPEMD160.c -o build/temp.linux-x86_64-2.7/src/RIPEMD160.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/RIPEMD160.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_RIPEMD160.so
    building 'Crypto.Cipher._AES' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/AES.c -o build/temp.linux-x86_64-2.7/src/AES.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/AES.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_AES.so
    building 'Crypto.Cipher._ARC2' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/lo[28/219]
on-2.7.9/include/python2.7 -c src/ARC2.c -o build/temp.linux-x86_64-2.7/src/ARC2.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/ARC2.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_ARC2.so
    building 'Crypto.Cipher._Blowfish' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/Blowfish.c -o build/temp.linux-x86_64-2.7/src/Blowfish.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/Blowfish.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_Blowfish.so
    building 'Crypto.Cipher._CAST' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/CAST.c -o build/temp.linux-x86_64-2.7/src/CAST.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/CAST.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_CAST.so
    building 'Crypto.Cipher._DES' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/
usr/local/python-2.7.9/include/python2.7 -c src/DES.c -o build/temp.linux-x86_64-2.7/src/DES.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/DES.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_DES.so
    building 'Crypto.Cipher._DES3' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/
usr/local/python-2.7.9/include/python2.7 -c src/DES3.c -o build/temp.linux-x86_64-2.7/src/DES3.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/DES3.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_DES3.so
    building 'Crypto.Cipher._ARC4' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/ARC4.c -o build/temp.linux-x86_64-2.7/src/ARC4.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/ARC4.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_ARC4.so
    building 'Crypto.Cipher._XOR' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/XOR.c -o build/temp.linux-x86_64-2.7/src/XOR.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/XOR.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_XOR.so
    building 'Crypto.Util.strxor' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/strxor.c -o build/temp.linux-x86_64-2.7/src/strxor.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/strxor.o -o build/lib.linux-x86_64-2.7/Crypto/Util/strxor.so
    building 'Crypto.Util._counter' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/local/pyth
on-2.7.9/include/python2.7 -c src/_counter.c -o build/temp.linux-x86_64-2.7/src/_counter.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/src/_counter.o -o build/lib.linux-x86_64-2.7/Crypto/Util/_counter.so

  Running setup.py install for Fabric
    Installing fab script to /home/mkovgan/virtualenvs/fabtest2.7.9/bin
Successfully installed Fabric-1.10.1 ecdsa-0.13 paramiko-1.15.2 pycrypto-2.6.1
 mkovgan  ⓔ fabtest2.7.9   master U:3  ~  fab -d task1
Traceback (most recent call last):
  File "/home/mkovgan/virtualenvs/fabtest2.7.9/lib/python2.7/site-packages/fabric/main.py", line 692, in main
    display_command(options.display)
  File "/home/mkovgan/virtualenvs/fabtest2.7.9/lib/python2.7/site-packages/fabric/main.py", line 477, in display_command
    task_details = command.__details__()
  File "/home/mkovgan/virtualenvs/fabtest2.7.9/lib/python2.7/site-packages/fabric/tasks.py", line 180, in __details__
    return get_task_details(self.wrapped)
  File "/home/mkovgan/virtualenvs/fabtest2.7.9/lib/python2.7/site-packages/fabric/tasks.py", line 42, in get_task_details
    argspec = inspect.getargspec(task)
  File "/usr/local/python-2.7.9/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <fabric.tasks.WrappedCallableTask object at 0x7f9722a408d0> is not a Python function
 mkovgan  ⓔ fabtest2.7.9   master U:3  ~  1  cat fabfile.py
from fabric.decorators import task, runs_once
@runs_once
@task
def task1(p1, p2):
    """
    nice docstr
    :param p1: p1
    :param p2: p2
    """
    pass

**Comment by mvk** [comment]
hi, Jeff.
weird thing, you should be able to reproduce.
I did:

   1. checked out clean master, checked out to commit: 182e7bcc [my changes
   were put on it]
   2. took tests/test_tasks.py from master, made a patch with my final
   changes to test_decorated_task [ATTACHED]
   3. applied the patch, and ran:
   *nosetests -v tests/test_tasks.py:TestTaskDetails.test_decorated_task*


*OUTPUT:*


*__details__() should print docstr for method with any number and order of
decorations ... ERROR*

*======================================================================*
*ERROR: __details__() should print docstr for method with any number and
order of decorations*
*----------------------------------------------------------------------*
*Traceback (most recent call last):*
*  File "/home/mkovgan/src/github/upstream/fabric/tests/test_tasks.py",
line 515, in test_decorated_task*
*    actual = decorated_task1.__details__()*
*  File "/home/mkovgan/src/github/upstream/fabric/fabric/tasks.py", line
180, in __details__*
*    return get_task_details(self.wrapped)*
*  File "/home/mkovgan/src/github/upstream/fabric/fabric/tasks.py", line
42, in get_task_details*
*    argspec = inspect.getargspec(task)*
*  File "/usr/lib64/python2.7/inspect.py", line 816, in getargspec*
*    raise TypeError('{!r} is not a Python function'.format(func))*
*TypeError: <fabric.tasks.WrappedCallableTask object at 0x7f7e6cd3ce50> is
not a Python function*

*----------------------------------------------------------------------*
*Ran 1 test in 0.001s*

*FAILED (errors=1)*


are we good ?




On Thu, Mar 12, 2015 at 1:51 AM, Jeff Forcier <notifications@github.com>
wrote:

> Yea, I can't reproduce this on my Mac, the test passes and the manual
> fabfile+fab -d you posted, also works just fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric/fabric/pull/1287#issuecomment-78398236>.
>



-- 
Maxim Kovgan

**Comment by mvk** [comment]
forgot the attachment :)


On Fri, Mar 13, 2015 at 11:54 AM, Maxim Kovgan <kovganm@gmail.com> wrote:

> hi, Jeff.
> weird thing, you should be able to reproduce.
> I did:
>
>    1. checked out clean master, checked out to commit: 182e7bcc [my
>    changes were put on it]
>    2. took tests/test_tasks.py from master, made a patch with my final
>    changes to test_decorated_task [ATTACHED]
>    3. applied the patch, and ran:
>    *nosetests -v tests/test_tasks.py:TestTaskDetails.test_decorated_task*
>
>
> *OUTPUT:*
>
>
> *__details__() should print docstr for method with any number and order of
> decorations ... ERROR*
>
> *======================================================================*
> *ERROR: __details__() should print docstr for method with any number and
> order of decorations*
> *----------------------------------------------------------------------*
> *Traceback (most recent call last):*
> *  File "/home/mkovgan/src/github/upstream/fabric/tests/test_tasks.py",
> line 515, in test_decorated_task*
> *    actual = decorated_task1.__details__()*
> *  File "/home/mkovgan/src/github/upstream/fabric/fabric/tasks.py", line
> 180, in __details__*
> *    return get_task_details(self.wrapped)*
> *  File "/home/mkovgan/src/github/upstream/fabric/fabric/tasks.py", line
> 42, in get_task_details*
> *    argspec = inspect.getargspec(task)*
> *  File "/usr/lib64/python2.7/inspect.py", line 816, in getargspec*
> *    raise TypeError('{!r} is not a Python function'.format(func))*
> *TypeError: <fabric.tasks.WrappedCallableTask object at 0x7f7e6cd3ce50> is
> not a Python function*
>
> *----------------------------------------------------------------------*
> *Ran 1 test in 0.001s*
>
> *FAILED (errors=1)*
>
>
> are we good ?
>
>
>
>
> On Thu, Mar 12, 2015 at 1:51 AM, Jeff Forcier <notifications@github.com>
> wrote:
>
>> Yea, I can't reproduce this on my Mac, the test passes and the manual
>> fabfile+fab -d you posted, also works just fine.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fabric/fabric/pull/1287#issuecomment-78398236>.
>>
>
>
>
> --
> Maxim Kovgan
>



-- 
Maxim Kovgan

**Pull request closed without merging**
