### PR TITLE
Keepalive flag

### PR DESCRIPTION
**Pull request by iurisilvio**
Ref #1807

### CODE REVIEW

**Comment by fruch** [comment]
@iurisilvio @bitprophet  anything holding this PR from being merged ?

**Comment by iurisilvio** [comment]
It is done, waiting for merge (or some feedback).

**Comment by wy-z** [comment]
@bitprophet  Thanks for your outstanding work~
Keepalive flag is necessary in some cases, can you take some moments to review this PR?

**Comment by devholland** [comment]
@bitprophet I would have needed that flag in my current project, too. Could you please include it?

**Pull request closed without merging**
