### PR TITLE
Update connection.py

### PR DESCRIPTION
**Pull request by MrAfrazKhan**
just clean scripts with white spaces.

### CODE REVIEW

**Comment by frenck** [comment]
It looks like this user is running for a Hacktoberfest t-shirt by creating a bunch of useless PRs on several repositories on this new GitHub account.

My advice would be to close this PR and add the `invalid` tag as well. Hacktoberfest processes the `invalid` tag by invalidating the contribution the user has made and won't count toward Hacktoberfest.

More information about this:

https://hacktoberfest.digitalocean.com/details#spam

The other PR's:
https://github.com/django/django/pull/11864/files
https://github.com/getsentry/sentry/pull/14908/files
https://github.com/wagtail/wagtail/pull/5598/files
https://github.com/fabric/fabric/pull/2020/files
https://github.com/home-assistant/home-assistant/pull/27124/files

**Comment by rpkilby** [comment]
That would explain it. I was wondering why they were opening up a bunch of whitespace PRs.

**Comment by frenck** [comment]
Yep, it happens a lot this time of the year, unfortunately. We (at Home Assistant) are often victim as well. I've decided this year, that is a user opens up a spam PR, I'll go looking at the other PR as well and leave a comment, like above.

Just to fight the spam. Hacktoberfest ain't hard, with some simple PR's one could still be useful. But I have zero respect for people spamming, like this one.

Please make sure to add the `invalid` label, that way, his actions render useless.

**Comment by rpkilby** [comment]
Thanks - I help maintain django rest framework, and we periodically see bursts of one-off fixes to docs and the like. I never realized that they might be linked to a hackathon.

Also, a colleague of mine pointed this out:
>  Last but not least, one PR to fix a typo is fine. 5 PRs to remove a stray whitespace... not.

Like you said, it's not hard to be useful.

**Comment by cclauss** [comment]
Can we please close this issue?

**Comment by davidjmemmett** [comment]
I can close this PR, but @bitprophet will have to add an `invalid` label if we're doing that (I don't have permission).

**Pull request closed without merging**
